    Three species of Iris (Iris setosa, Iris virginica and Iris versicolor)
    Four features were measured from each sample: the length and the width of the sepals and petals.


<img src = 'pics/setosa.jpg'> <img src = 'pics/virginica.jpg'> <img src = 'pics/versicolor.jpg'> 

In [1]:
# Importing the libraries
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

In [2]:
# Importing the dataset
trainData = pd.read_csv('Iris_data/Iris_data.csv')
trainData

sepal length  sepal width  petal length  petal width  Class
0             5.1          3.5           1.4          0.2      1
1             4.9          3.0           1.4          0.2      1
2             4.7          3.2           1.3          0.2      1
3             4.6          3.1           1.5          0.2      1
4             5.4          3.9           1.7          0.4      1
5             4.6          3.4           1.4          0.3      1
6             5.0          3.4           1.5          0.2      1
7             4.4          2.9           1.4          0.2      1
8             4.9          3.1           1.5          0.1      1
9             4.8          3.4           1.6          0.2      1
10            4.3          3.0           1.1          0.1      1
11            5.8          4.0           1.2          0.2      1
12            5.7          4.4           1.5          0.4      1
13            5.4          3.9           1.3          0.4      1
14            5.1          3.5           1.4          0.3      1
15            5.7          3.8           1.7          0.3      1
16            5.1          3.8           1.5          0.3      1
17            5.4          3.4           1.7          0.2      1
18            5.1          3.7           1.5          0.4      1
19            4.6          3.6           1.0          0.2      1
20            4.8          3.4           1.9          0.2      1
21            5.2          3.4           1.4          0.2      1
22            4.7          3.2           1.6          0.2      1
23            4.8          3.1           1.6          0.2      1
24            5.2          4.1           1.5          0.1      1
25            5.5          4.2           1.4          0.2      1
26            4.9          3.1           1.5          0.1      1
27            4.9          3.1           1.5          0.1      1
28            4.4          3.0           1.3          0.2      1
29            5.1          3.4           1.5          0.2      1
..            ...          ...           ...          ...    ...
84            5.8          2.8           5.1          2.4      3
85            6.4          3.2           5.3          2.3      3
86            6.5          3.0           5.5          1.8      3
87            7.7          3.8           6.7          2.2      3
88            7.7          2.6           6.9          2.3      3
89            5.6          2.8           4.9          2.0      3
90            7.7          2.8           6.7          2.0      3
91            6.3          2.7           4.9          1.8      3
92            7.2          3.2           6.0          1.8      3
93            6.1          3.0           4.9          1.8      3
94            6.4          2.8           5.6          2.1      3
95            7.2          3.0           5.8          1.6      3
96            7.4          2.8           6.1          1.9      3
97            7.9          3.8           6.4          2.0      3
98            6.4          2.8           5.6          2.2      3
99            6.3          2.8           5.1          1.5      3
100           6.1          2.6           5.6          1.4      3
101           7.7          3.0           6.1          2.3      3
102           6.3          3.4           5.6          2.4      3
103           6.4          3.1           5.5          1.8      3
104           6.0          3.0           4.8          1.8      3
105           6.9          3.1           5.4          2.1      3
106           6.7          3.1           5.6          2.4      3
107           5.8          2.7           5.1          1.9      3
108           6.8          3.2           5.9          2.3      3
109           6.7          3.3           5.7          2.5      3
110           6.3          2.5           5.0          1.9      3
111           6.5          3.0           5.2          2.0      3
112           6.2          3.4           5.4          2.3      3
113           5.9          3.0          

In [13]:
X_train = trainData.iloc[:, :-1].values
X_train

array([[5.1, 3.5, 1.4, 0.2],
       [4.9, 3. , 1.4, 0.2],
       [4.7, 3.2, 1.3, 0.2],
       [4.6, 3.1, 1.5, 0.2],
       [5.4, 3.9, 1.7, 0.4],
       [4.6, 3.4, 1.4, 0.3],
       [5. , 3.4, 1.5, 0.2],
       [4.4, 2.9, 1.4, 0.2],
       [4.9, 3.1, 1.5, 0.1],
       [4.8, 3.4, 1.6, 0.2],
       [4.3, 3. , 1.1, 0.1],
       [5.8, 4. , 1.2, 0.2],
       [5.7, 4.4, 1.5, 0.4],
       [5.4, 3.9, 1.3, 0.4],
       [5.1, 3.5, 1.4, 0.3],
       [5.7, 3.8, 1.7, 0.3],
       [5.1, 3.8, 1.5, 0.3],
       [5.4, 3.4, 1.7, 0.2],
       [5.1, 3.7, 1.5, 0.4],
       [4.6, 3.6, 1. , 0.2],
       [4.8, 3.4, 1.9, 0.2],
       [5.2, 3.4, 1.4, 0.2],
       [4.7, 3.2, 1.6, 0.2],
       [4.8, 3.1, 1.6, 0.2],
       [5.2, 4.1, 1.5, 0.1],
       [5.5, 4.2, 1.4, 0.2],
       [4.9, 3.1, 1.5, 0.1],
       [4.9, 3.1, 1.5, 0.1],
       [4.4, 3. , 1.3, 0.2],
       [5.1, 3.4, 1.5, 0.2],
       [5. , 3.5, 1.3, 0.3],
       [4.5, 2.3, 1.3, 0.3],
       [4.4, 3.2, 1.3, 0.2],
       [5. , 3.5, 1.6, 0.6],
       [5.1, 3

In [14]:
y_train = trainData.iloc[:, 4].values
y_train

array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3,
       3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3,
       3, 3, 3, 3], dtype=int64)

In [4]:
# Fitting Naive Bayes to the Training set
from sklearn.naive_bayes import GaussianNB
classifier = GaussianNB()
classifier.fit(X_train, y_train)

GaussianNB(priors=None)

In [15]:
# Predicting the Test set results
y_pred = classifier.predict(X_train)
y_pred

array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 3, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 3, 2, 2, 2, 3, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 3, 3, 3, 3, 3, 2, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3,
       3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 2, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3,
       3, 3, 3, 3], dtype=int64)

In [6]:
# Making the Confusion Matrix
from sklearn.metrics import confusion_matrix
cm = confusion_matrix(y_train, y_pred)
cm

array([[37,  0,  0],
       [ 0, 32,  3],
       [ 0,  2, 40]], dtype=int64)

In [7]:
classifier.score(X_train,y_train)

0.956140350877193

### Test model

In [8]:
# Import dataset
testData = pd.read_csv('Iris_data/Iris_test.csv')
testData

sepal length  sepal width  petal length  petal width  Class
0            5.0          3.6           1.4          0.2      1
1            5.4          3.7           1.5          0.2      1
2            4.8          3.0           1.4          0.1      1
3            5.1          3.3           1.7          0.5      1
4            5.0          3.0           1.6          0.2      1
5            5.0          3.4           1.6          0.4      1
6            5.2          3.5           1.5          0.2      1
7            5.4          3.4           1.5          0.4      1
8            5.0          3.2           1.2          0.2      1
9            5.5          3.5           1.3          0.2      1
10           4.6          3.2           1.4          0.2      1
11           5.3          3.7           1.5          0.2      1
12           5.0          3.3           1.4          0.2      1
13           7.0          3.2           4.7          1.4      2
14           6.4          3.2           4.5          1.5      2
15           6.3          3.3           4.7          1.6      2
16           6.6          2.9           4.6          1.3      2
17           6.0          2.2           4.0          1.0      2
18           5.6          2.9           3.6          1.3      2
19           5.6          2.5           3.9          1.1      2
20           6.3          2.5           4.9          1.5      2
21           6.1          2.8           4.7          1.2      2
22           6.8          2.8           4.8          1.4      2
23           5.5          2.4           3.7          1.0      2
24           6.0          2.7           5.1          1.6      2
25           6.0          3.4           4.5          1.6      2
26           5.7          2.9           4.2          1.3      2
27           5.1          2.5           3.0          1.1      2
28           6.5          3.0           5.8          2.2      3
29           7.3          2.9           6.3          1.8      3
30           6.0          2.2           5.0          1.5      3
31           6.9          3.2           5.7          2.3      3
32           6.7          3.3           5.7          2.1      3
33           6.2          2.8           4.8          1.8      3
34           6.9          3.1           5.1          2.3      3
35           6.7          3.0           5.2          2.3      3

In [9]:
X_test = testData.iloc[:, :4].values
y_test = testData.iloc[:, 4].values

In [10]:
# Predicting the Test set results
y_pred = classifier.predict(X_test)

In [11]:
# Making the Confusion Matrix
cm = confusion_matrix(y_test, y_pred)
cm

array([[13,  0,  0],
       [ 0, 14,  1],
       [ 0,  1,  7]], dtype=int64)

In [12]:
classifier.score(X_test,y_test)

0.9444444444444444